//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChatStream.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Post))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Follow))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Friend))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Like))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.DMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.GMember))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.GMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebChatStream.ServiceReference1.Comment))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Post : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntrDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntrDate {
            get {
                return this.EntrDateField;
            }
            set {
                if ((this.EntrDateField.Equals(value) != true)) {
                    this.EntrDateField = value;
                    this.RaisePropertyChanged("EntrDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uname {
            get {
                return this.UnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnameField, value) != true)) {
                    this.UnameField = value;
                    this.RaisePropertyChanged("Uname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Follow", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Follow : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User FollowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User FollowingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User Follower {
            get {
                return this.FollowerField;
            }
            set {
                if ((object.ReferenceEquals(this.FollowerField, value) != true)) {
                    this.FollowerField = value;
                    this.RaisePropertyChanged("Follower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User Following {
            get {
                return this.FollowingField;
            }
            set {
                if ((object.ReferenceEquals(this.FollowingField, value) != true)) {
                    this.FollowingField = value;
                    this.RaisePropertyChanged("Following");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friend", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Friend : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User User1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User User2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Approved {
            get {
                return this.ApprovedField;
            }
            set {
                if ((this.ApprovedField.Equals(value) != true)) {
                    this.ApprovedField = value;
                    this.RaisePropertyChanged("Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User2 {
            get {
                return this.User2Field;
            }
            set {
                if ((object.ReferenceEquals(this.User2Field, value) != true)) {
                    this.User2Field = value;
                    this.RaisePropertyChanged("User2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Like", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Like : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.Post PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.Post Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMessage", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class DMessage : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User DestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User SourceUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User DestUser {
            get {
                return this.DestUserField;
            }
            set {
                if ((object.ReferenceEquals(this.DestUserField, value) != true)) {
                    this.DestUserField = value;
                    this.RaisePropertyChanged("DestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seen {
            get {
                return this.SeenField;
            }
            set {
                if ((this.SeenField.Equals(value) != true)) {
                    this.SeenField = value;
                    this.RaisePropertyChanged("Seen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User SourceUser {
            get {
                return this.SourceUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceUserField, value) != true)) {
                    this.SourceUserField = value;
                    this.RaisePropertyChanged("SourceUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Group : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GNnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GNname {
            get {
                return this.GNnameField;
            }
            set {
                if ((object.ReferenceEquals(this.GNnameField, value) != true)) {
                    this.GNnameField = value;
                    this.RaisePropertyChanged("GNname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publicity {
            get {
                return this.PublicityField;
            }
            set {
                if ((this.PublicityField.Equals(value) != true)) {
                    this.PublicityField = value;
                    this.RaisePropertyChanged("Publicity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMember", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class GMember : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMessage", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class GMessage : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Comment : WebChatStream.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.Post PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebChatStream.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.Post Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebChatStream.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebChatStream.ServiceReference1.CompositeType GetDataUsingDataContract(WebChatStream.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebChatStream.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComment", ReplyAction="http://tempuri.org/IService1/DeleteCommentResponse")]
        void DeleteComment(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComment", ReplyAction="http://tempuri.org/IService1/DeleteCommentResponse")]
        System.Threading.Tasks.Task DeleteCommentAsync(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertComment", ReplyAction="http://tempuri.org/IService1/InsertCommentResponse")]
        void InsertComment(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertComment", ReplyAction="http://tempuri.org/IService1/InsertCommentResponse")]
        System.Threading.Tasks.Task InsertCommentAsync(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateComment", ReplyAction="http://tempuri.org/IService1/UpdateCommentResponse")]
        void UpdateComment(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateComment", ReplyAction="http://tempuri.org/IService1/UpdateCommentResponse")]
        System.Threading.Tasks.Task UpdateCommentAsync(WebChatStream.ServiceReference1.Comment entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCommentByPost", ReplyAction="http://tempuri.org/IService1/SelectCommentByPostResponse")]
        WebChatStream.ServiceReference1.Comment[] SelectCommentByPost(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCommentByPost", ReplyAction="http://tempuri.org/IService1/SelectCommentByPostResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Comment[]> SelectCommentByPostAsync(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUser", ReplyAction="http://tempuri.org/IService1/InsertUserResponse")]
        WebChatStream.ServiceReference1.User InsertUser(WebChatStream.ServiceReference1.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUser", ReplyAction="http://tempuri.org/IService1/InsertUserResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> InsertUserAsync(WebChatStream.ServiceReference1.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        WebChatStream.ServiceReference1.User Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByUserID", ReplyAction="http://tempuri.org/IService1/SelectByUserIDResponse")]
        WebChatStream.ServiceReference1.User SelectByUserID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByUserID", ReplyAction="http://tempuri.org/IService1/SelectByUserIDResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> SelectByUserIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserByUName", ReplyAction="http://tempuri.org/IService1/SelectUserByUNameResponse")]
        WebChatStream.ServiceReference1.User[] SelectUserByUName(string Uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserByUName", ReplyAction="http://tempuri.org/IService1/SelectUserByUNameResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectUserByUNameAsync(string Uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        WebChatStream.ServiceReference1.User SignUp(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> SignUpAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFollow", ReplyAction="http://tempuri.org/IService1/InsertFollowResponse")]
        WebChatStream.ServiceReference1.Follow InsertFollow(WebChatStream.ServiceReference1.Follow follow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFollow", ReplyAction="http://tempuri.org/IService1/InsertFollowResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Follow> InsertFollowAsync(WebChatStream.ServiceReference1.Follow follow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFollow", ReplyAction="http://tempuri.org/IService1/DeleteFollowResponse")]
        void DeleteFollow(WebChatStream.ServiceReference1.Follow follow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFollow", ReplyAction="http://tempuri.org/IService1/DeleteFollowResponse")]
        System.Threading.Tasks.Task DeleteFollowAsync(WebChatStream.ServiceReference1.Follow follow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFollowed", ReplyAction="http://tempuri.org/IService1/SelectFollowedResponse")]
        WebChatStream.ServiceReference1.Follow[] SelectFollowed(WebChatStream.ServiceReference1.User follower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFollowed", ReplyAction="http://tempuri.org/IService1/SelectFollowedResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Follow[]> SelectFollowedAsync(WebChatStream.ServiceReference1.User follower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsFollowing", ReplyAction="http://tempuri.org/IService1/IsFollowingResponse")]
        bool IsFollowing(WebChatStream.ServiceReference1.Follow follower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsFollowing", ReplyAction="http://tempuri.org/IService1/IsFollowingResponse")]
        System.Threading.Tasks.Task<bool> IsFollowingAsync(WebChatStream.ServiceReference1.Follow follower);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFriend", ReplyAction="http://tempuri.org/IService1/InsertFriendResponse")]
        WebChatStream.ServiceReference1.Friend InsertFriend(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFriend", ReplyAction="http://tempuri.org/IService1/InsertFriendResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend> InsertFriendAsync(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFriend", ReplyAction="http://tempuri.org/IService1/DeleteFriendResponse")]
        void DeleteFriend(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFriend", ReplyAction="http://tempuri.org/IService1/DeleteFriendResponse")]
        System.Threading.Tasks.Task DeleteFriendAsync(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreFriends", ReplyAction="http://tempuri.org/IService1/AreFriendsResponse")]
        bool AreFriends(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreFriends", ReplyAction="http://tempuri.org/IService1/AreFriendsResponse")]
        System.Threading.Tasks.Task<bool> AreFriendsAsync(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFriend", ReplyAction="http://tempuri.org/IService1/SelectFriendResponse")]
        WebChatStream.ServiceReference1.Friend SelectFriend(WebChatStream.ServiceReference1.User user1, WebChatStream.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectFriend", ReplyAction="http://tempuri.org/IService1/SelectFriendResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend> SelectFriendAsync(WebChatStream.ServiceReference1.User user1, WebChatStream.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectRecivedReq", ReplyAction="http://tempuri.org/IService1/SelectRecivedReqResponse")]
        WebChatStream.ServiceReference1.Friend[] SelectRecivedReq(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectRecivedReq", ReplyAction="http://tempuri.org/IService1/SelectRecivedReqResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend[]> SelectRecivedReqAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserFriends", ReplyAction="http://tempuri.org/IService1/SelectUserFriendsResponse")]
        WebChatStream.ServiceReference1.Friend[] SelectUserFriends(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserFriends", ReplyAction="http://tempuri.org/IService1/SelectUserFriendsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend[]> SelectUserFriendsAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ApproveFriend", ReplyAction="http://tempuri.org/IService1/ApproveFriendResponse")]
        void ApproveFriend(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ApproveFriend", ReplyAction="http://tempuri.org/IService1/ApproveFriendResponse")]
        System.Threading.Tasks.Task ApproveFriendAsync(WebChatStream.ServiceReference1.Friend friend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLike", ReplyAction="http://tempuri.org/IService1/InsertLikeResponse")]
        WebChatStream.ServiceReference1.Like InsertLike(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLike", ReplyAction="http://tempuri.org/IService1/InsertLikeResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Like> InsertLikeAsync(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLike", ReplyAction="http://tempuri.org/IService1/DeleteLikeResponse")]
        void DeleteLike(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLike", ReplyAction="http://tempuri.org/IService1/DeleteLikeResponse")]
        System.Threading.Tasks.Task DeleteLikeAsync(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountLikes", ReplyAction="http://tempuri.org/IService1/CountLikesResponse")]
        int CountLikes(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountLikes", ReplyAction="http://tempuri.org/IService1/CountLikesResponse")]
        System.Threading.Tasks.Task<int> CountLikesAsync(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsLiked", ReplyAction="http://tempuri.org/IService1/IsLikedResponse")]
        bool IsLiked(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsLiked", ReplyAction="http://tempuri.org/IService1/IsLikedResponse")]
        System.Threading.Tasks.Task<bool> IsLikedAsync(WebChatStream.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPost", ReplyAction="http://tempuri.org/IService1/InsertPostResponse")]
        WebChatStream.ServiceReference1.Post InsertPost(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPost", ReplyAction="http://tempuri.org/IService1/InsertPostResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post> InsertPostAsync(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        void DeletePost(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        System.Threading.Tasks.Task DeletePostAsync(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePost", ReplyAction="http://tempuri.org/IService1/UpdatePostResponse")]
        void UpdatePost(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePost", ReplyAction="http://tempuri.org/IService1/UpdatePostResponse")]
        System.Threading.Tasks.Task UpdatePostAsync(WebChatStream.ServiceReference1.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserFeed", ReplyAction="http://tempuri.org/IService1/SelectUserFeedResponse")]
        WebChatStream.ServiceReference1.Post[] SelectUserFeed(WebChatStream.ServiceReference1.User mainUser, WebChatStream.ServiceReference1.User req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserFeed", ReplyAction="http://tempuri.org/IService1/SelectUserFeedResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectUserFeedAsync(WebChatStream.ServiceReference1.User mainUser, WebChatStream.ServiceReference1.User req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectMyFeed", ReplyAction="http://tempuri.org/IService1/SelectMyFeedResponse")]
        WebChatStream.ServiceReference1.Post[] SelectMyFeed(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectMyFeed", ReplyAction="http://tempuri.org/IService1/SelectMyFeedResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectMyFeedAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostsByUser", ReplyAction="http://tempuri.org/IService1/SelectPostsByUserResponse")]
        WebChatStream.ServiceReference1.Post[] SelectPostsByUser(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostsByUser", ReplyAction="http://tempuri.org/IService1/SelectPostsByUserResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectPostsByUserAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostsByUID", ReplyAction="http://tempuri.org/IService1/SelectPostsByUIDResponse")]
        WebChatStream.ServiceReference1.Post[] SelectPostsByUID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostsByUID", ReplyAction="http://tempuri.org/IService1/SelectPostsByUIDResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectPostsByUIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostByID", ReplyAction="http://tempuri.org/IService1/SelectPostByIDResponse")]
        WebChatStream.ServiceReference1.Post SelectPostByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPostByID", ReplyAction="http://tempuri.org/IService1/SelectPostByIDResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post> SelectPostByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDM", ReplyAction="http://tempuri.org/IService1/InsertDMResponse")]
        void InsertDM(WebChatStream.ServiceReference1.DMessage dMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDM", ReplyAction="http://tempuri.org/IService1/InsertDMResponse")]
        System.Threading.Tasks.Task InsertDMAsync(WebChatStream.ServiceReference1.DMessage dMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDMChats", ReplyAction="http://tempuri.org/IService1/GetAllDMChatsResponse")]
        WebChatStream.ServiceReference1.User[] GetAllDMChats(WebChatStream.ServiceReference1.User main);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDMChats", ReplyAction="http://tempuri.org/IService1/GetAllDMChatsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> GetAllDMChatsAsync(WebChatStream.ServiceReference1.User main);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllDMsChat", ReplyAction="http://tempuri.org/IService1/SelectAllDMsChatResponse")]
        WebChatStream.ServiceReference1.DMessage[] SelectAllDMsChat(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllDMsChat", ReplyAction="http://tempuri.org/IService1/SelectAllDMsChatResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.DMessage[]> SelectAllDMsChatAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreChatting", ReplyAction="http://tempuri.org/IService1/AreChattingResponse")]
        bool AreChatting(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreChatting", ReplyAction="http://tempuri.org/IService1/AreChattingResponse")]
        System.Threading.Tasks.Task<bool> AreChattingAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUnSeenDM", ReplyAction="http://tempuri.org/IService1/SelectUnSeenDMResponse")]
        WebChatStream.ServiceReference1.DMessage[] SelectUnSeenDM(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUnSeenDM", ReplyAction="http://tempuri.org/IService1/SelectUnSeenDMResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.DMessage[]> SelectUnSeenDMAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChatsDMUpdateState", ReplyAction="http://tempuri.org/IService1/GetChatsDMUpdateStateResponse")]
        int GetChatsDMUpdateState(WebChatStream.ServiceReference1.User main);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChatsDMUpdateState", ReplyAction="http://tempuri.org/IService1/GetChatsDMUpdateStateResponse")]
        System.Threading.Tasks.Task<int> GetChatsDMUpdateStateAsync(WebChatStream.ServiceReference1.User main);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupByID", ReplyAction="http://tempuri.org/IService1/GetGroupByIDResponse")]
        WebChatStream.ServiceReference1.Group GetGroupByID(int groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupByID", ReplyAction="http://tempuri.org/IService1/GetGroupByIDResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group> GetGroupByIDAsync(int groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupsByName", ReplyAction="http://tempuri.org/IService1/GetGroupsByNameResponse")]
        WebChatStream.ServiceReference1.Group[] GetGroupsByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupsByName", ReplyAction="http://tempuri.org/IService1/GetGroupsByNameResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> GetGroupsByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGroup", ReplyAction="http://tempuri.org/IService1/InsertGroupResponse")]
        void InsertGroup(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User creator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGroup", ReplyAction="http://tempuri.org/IService1/InsertGroupResponse")]
        System.Threading.Tasks.Task InsertGroupAsync(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User creator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGroup", ReplyAction="http://tempuri.org/IService1/UpdateGroupResponse")]
        void UpdateGroup(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGroup", ReplyAction="http://tempuri.org/IService1/UpdateGroupResponse")]
        System.Threading.Tasks.Task UpdateGroupAsync(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGroup", ReplyAction="http://tempuri.org/IService1/DeleteGroupResponse")]
        void DeleteGroup(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGroup", ReplyAction="http://tempuri.org/IService1/DeleteGroupResponse")]
        System.Threading.Tasks.Task DeleteGroupAsync(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGMemeber", ReplyAction="http://tempuri.org/IService1/InsertGMemeberResponse")]
        WebChatStream.ServiceReference1.GMember InsertGMemeber(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGMemeber", ReplyAction="http://tempuri.org/IService1/InsertGMemeberResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMember> InsertGMemeberAsync(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGMember", ReplyAction="http://tempuri.org/IService1/DeleteGMemberResponse")]
        void DeleteGMember(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGMember", ReplyAction="http://tempuri.org/IService1/DeleteGMemberResponse")]
        System.Threading.Tasks.Task DeleteGMemberAsync(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGMemberStatus", ReplyAction="http://tempuri.org/IService1/UpdateGMemberStatusResponse")]
        void UpdateGMemberStatus(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGMemberStatus", ReplyAction="http://tempuri.org/IService1/UpdateGMemberStatusResponse")]
        System.Threading.Tasks.Task UpdateGMemberStatusAsync(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupMembers", ReplyAction="http://tempuri.org/IService1/GetGroupMembersResponse")]
        WebChatStream.ServiceReference1.GMember[] GetGroupMembers(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupMembers", ReplyAction="http://tempuri.org/IService1/GetGroupMembersResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMember[]> GetGroupMembersAsync(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGroupAdmins", ReplyAction="http://tempuri.org/IService1/SelectGroupAdminsResponse")]
        WebChatStream.ServiceReference1.User[] SelectGroupAdmins(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGroupAdmins", ReplyAction="http://tempuri.org/IService1/SelectGroupAdminsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectGroupAdminsAsync(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGroupNonAdmins", ReplyAction="http://tempuri.org/IService1/SelectGroupNonAdminsResponse")]
        WebChatStream.ServiceReference1.User[] SelectGroupNonAdmins(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGroupNonAdmins", ReplyAction="http://tempuri.org/IService1/SelectGroupNonAdminsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectGroupNonAdminsAsync(WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsGroupAdmin", ReplyAction="http://tempuri.org/IService1/IsGroupAdminResponse")]
        bool IsGroupAdmin(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsGroupAdmin", ReplyAction="http://tempuri.org/IService1/IsGroupAdminResponse")]
        System.Threading.Tasks.Task<bool> IsGroupAdminAsync(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsGroupMember", ReplyAction="http://tempuri.org/IService1/IsGroupMemberResponse")]
        bool IsGroupMember(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsGroupMember", ReplyAction="http://tempuri.org/IService1/IsGroupMemberResponse")]
        System.Threading.Tasks.Task<bool> IsGroupMemberAsync(WebChatStream.ServiceReference1.GMember member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGMessage", ReplyAction="http://tempuri.org/IService1/InsertGMessageResponse")]
        WebChatStream.ServiceReference1.GMessage InsertGMessage(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGMessage", ReplyAction="http://tempuri.org/IService1/InsertGMessageResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage> InsertGMessageAsync(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGMessage", ReplyAction="http://tempuri.org/IService1/DeleteGMessageResponse")]
        void DeleteGMessage(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGMessage", ReplyAction="http://tempuri.org/IService1/DeleteGMessageResponse")]
        System.Threading.Tasks.Task DeleteGMessageAsync(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGMessage", ReplyAction="http://tempuri.org/IService1/UpdateGMessageResponse")]
        void UpdateGMessage(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGMessage", ReplyAction="http://tempuri.org/IService1/UpdateGMessageResponse")]
        System.Threading.Tasks.Task UpdateGMessageAsync(WebChatStream.ServiceReference1.GMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGMessages", ReplyAction="http://tempuri.org/IService1/SelectGMessagesResponse")]
        WebChatStream.ServiceReference1.GMessage[] SelectGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGMessages", ReplyAction="http://tempuri.org/IService1/SelectGMessagesResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> SelectGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGMessages", ReplyAction="http://tempuri.org/IService1/GetGMessagesResponse")]
        WebChatStream.ServiceReference1.GMessage[] GetGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGMessages", ReplyAction="http://tempuri.org/IService1/GetGMessagesResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> GetGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnSeenGMessages", ReplyAction="http://tempuri.org/IService1/GetUnSeenGMessagesResponse")]
        WebChatStream.ServiceReference1.GMessage[] GetUnSeenGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnSeenGMessages", ReplyAction="http://tempuri.org/IService1/GetUnSeenGMessagesResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> GetUnSeenGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyGroups", ReplyAction="http://tempuri.org/IService1/GetMyGroupsResponse")]
        WebChatStream.ServiceReference1.Group[] GetMyGroups(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyGroups", ReplyAction="http://tempuri.org/IService1/GetMyGroupsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> GetMyGroupsAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyGroupsUpdateState", ReplyAction="http://tempuri.org/IService1/GetMyGroupsUpdateStateResponse")]
        int GetMyGroupsUpdateState(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyGroupsUpdateState", ReplyAction="http://tempuri.org/IService1/GetMyGroupsUpdateStateResponse")]
        System.Threading.Tasks.Task<int> GetMyGroupsUpdateStateAsync(WebChatStream.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchPublicGroups", ReplyAction="http://tempuri.org/IService1/SearchPublicGroupsResponse")]
        WebChatStream.ServiceReference1.Group[] SearchPublicGroups(string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchPublicGroups", ReplyAction="http://tempuri.org/IService1/SearchPublicGroupsResponse")]
        System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> SearchPublicGroupsAsync(string groupName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebChatStream.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebChatStream.ServiceReference1.IService1>, WebChatStream.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebChatStream.ServiceReference1.CompositeType GetDataUsingDataContract(WebChatStream.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WebChatStream.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void DeleteComment(WebChatStream.ServiceReference1.Comment entity) {
            base.Channel.DeleteComment(entity);
        }
        
        public System.Threading.Tasks.Task DeleteCommentAsync(WebChatStream.ServiceReference1.Comment entity) {
            return base.Channel.DeleteCommentAsync(entity);
        }
        
        public void InsertComment(WebChatStream.ServiceReference1.Comment entity) {
            base.Channel.InsertComment(entity);
        }
        
        public System.Threading.Tasks.Task InsertCommentAsync(WebChatStream.ServiceReference1.Comment entity) {
            return base.Channel.InsertCommentAsync(entity);
        }
        
        public void UpdateComment(WebChatStream.ServiceReference1.Comment entity) {
            base.Channel.UpdateComment(entity);
        }
        
        public System.Threading.Tasks.Task UpdateCommentAsync(WebChatStream.ServiceReference1.Comment entity) {
            return base.Channel.UpdateCommentAsync(entity);
        }
        
        public WebChatStream.ServiceReference1.Comment[] SelectCommentByPost(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.SelectCommentByPost(post);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Comment[]> SelectCommentByPostAsync(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.SelectCommentByPostAsync(post);
        }
        
        public WebChatStream.ServiceReference1.User InsertUser(WebChatStream.ServiceReference1.User entity) {
            return base.Channel.InsertUser(entity);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> InsertUserAsync(WebChatStream.ServiceReference1.User entity) {
            return base.Channel.InsertUserAsync(entity);
        }
        
        public WebChatStream.ServiceReference1.User Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public WebChatStream.ServiceReference1.User SelectByUserID(int ID) {
            return base.Channel.SelectByUserID(ID);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> SelectByUserIDAsync(int ID) {
            return base.Channel.SelectByUserIDAsync(ID);
        }
        
        public WebChatStream.ServiceReference1.User[] SelectUserByUName(string Uname) {
            return base.Channel.SelectUserByUName(Uname);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectUserByUNameAsync(string Uname) {
            return base.Channel.SelectUserByUNameAsync(Uname);
        }
        
        public void UpdateUser(WebChatStream.ServiceReference1.User user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void DeleteUser(string userName, string password) {
            base.Channel.DeleteUser(userName, password);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(string userName, string password) {
            return base.Channel.DeleteUserAsync(userName, password);
        }
        
        public WebChatStream.ServiceReference1.User SignUp(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SignUp(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User> SignUpAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SignUpAsync(user);
        }
        
        public WebChatStream.ServiceReference1.Follow InsertFollow(WebChatStream.ServiceReference1.Follow follow) {
            return base.Channel.InsertFollow(follow);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Follow> InsertFollowAsync(WebChatStream.ServiceReference1.Follow follow) {
            return base.Channel.InsertFollowAsync(follow);
        }
        
        public void DeleteFollow(WebChatStream.ServiceReference1.Follow follow) {
            base.Channel.DeleteFollow(follow);
        }
        
        public System.Threading.Tasks.Task DeleteFollowAsync(WebChatStream.ServiceReference1.Follow follow) {
            return base.Channel.DeleteFollowAsync(follow);
        }
        
        public WebChatStream.ServiceReference1.Follow[] SelectFollowed(WebChatStream.ServiceReference1.User follower) {
            return base.Channel.SelectFollowed(follower);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Follow[]> SelectFollowedAsync(WebChatStream.ServiceReference1.User follower) {
            return base.Channel.SelectFollowedAsync(follower);
        }
        
        public bool IsFollowing(WebChatStream.ServiceReference1.Follow follower) {
            return base.Channel.IsFollowing(follower);
        }
        
        public System.Threading.Tasks.Task<bool> IsFollowingAsync(WebChatStream.ServiceReference1.Follow follower) {
            return base.Channel.IsFollowingAsync(follower);
        }
        
        public WebChatStream.ServiceReference1.Friend InsertFriend(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.InsertFriend(friend);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend> InsertFriendAsync(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.InsertFriendAsync(friend);
        }
        
        public void DeleteFriend(WebChatStream.ServiceReference1.Friend friend) {
            base.Channel.DeleteFriend(friend);
        }
        
        public System.Threading.Tasks.Task DeleteFriendAsync(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.DeleteFriendAsync(friend);
        }
        
        public bool AreFriends(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.AreFriends(friend);
        }
        
        public System.Threading.Tasks.Task<bool> AreFriendsAsync(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.AreFriendsAsync(friend);
        }
        
        public WebChatStream.ServiceReference1.Friend SelectFriend(WebChatStream.ServiceReference1.User user1, WebChatStream.ServiceReference1.User user2) {
            return base.Channel.SelectFriend(user1, user2);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend> SelectFriendAsync(WebChatStream.ServiceReference1.User user1, WebChatStream.ServiceReference1.User user2) {
            return base.Channel.SelectFriendAsync(user1, user2);
        }
        
        public WebChatStream.ServiceReference1.Friend[] SelectRecivedReq(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectRecivedReq(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend[]> SelectRecivedReqAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectRecivedReqAsync(user);
        }
        
        public WebChatStream.ServiceReference1.Friend[] SelectUserFriends(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectUserFriends(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Friend[]> SelectUserFriendsAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectUserFriendsAsync(user);
        }
        
        public void ApproveFriend(WebChatStream.ServiceReference1.Friend friend) {
            base.Channel.ApproveFriend(friend);
        }
        
        public System.Threading.Tasks.Task ApproveFriendAsync(WebChatStream.ServiceReference1.Friend friend) {
            return base.Channel.ApproveFriendAsync(friend);
        }
        
        public WebChatStream.ServiceReference1.Like InsertLike(WebChatStream.ServiceReference1.Like like) {
            return base.Channel.InsertLike(like);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Like> InsertLikeAsync(WebChatStream.ServiceReference1.Like like) {
            return base.Channel.InsertLikeAsync(like);
        }
        
        public void DeleteLike(WebChatStream.ServiceReference1.Like like) {
            base.Channel.DeleteLike(like);
        }
        
        public System.Threading.Tasks.Task DeleteLikeAsync(WebChatStream.ServiceReference1.Like like) {
            return base.Channel.DeleteLikeAsync(like);
        }
        
        public int CountLikes(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.CountLikes(post);
        }
        
        public System.Threading.Tasks.Task<int> CountLikesAsync(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.CountLikesAsync(post);
        }
        
        public bool IsLiked(WebChatStream.ServiceReference1.Like like) {
            return base.Channel.IsLiked(like);
        }
        
        public System.Threading.Tasks.Task<bool> IsLikedAsync(WebChatStream.ServiceReference1.Like like) {
            return base.Channel.IsLikedAsync(like);
        }
        
        public WebChatStream.ServiceReference1.Post InsertPost(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.InsertPost(post);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post> InsertPostAsync(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.InsertPostAsync(post);
        }
        
        public void DeletePost(WebChatStream.ServiceReference1.Post post) {
            base.Channel.DeletePost(post);
        }
        
        public System.Threading.Tasks.Task DeletePostAsync(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.DeletePostAsync(post);
        }
        
        public void UpdatePost(WebChatStream.ServiceReference1.Post post) {
            base.Channel.UpdatePost(post);
        }
        
        public System.Threading.Tasks.Task UpdatePostAsync(WebChatStream.ServiceReference1.Post post) {
            return base.Channel.UpdatePostAsync(post);
        }
        
        public WebChatStream.ServiceReference1.Post[] SelectUserFeed(WebChatStream.ServiceReference1.User mainUser, WebChatStream.ServiceReference1.User req) {
            return base.Channel.SelectUserFeed(mainUser, req);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectUserFeedAsync(WebChatStream.ServiceReference1.User mainUser, WebChatStream.ServiceReference1.User req) {
            return base.Channel.SelectUserFeedAsync(mainUser, req);
        }
        
        public WebChatStream.ServiceReference1.Post[] SelectMyFeed(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectMyFeed(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectMyFeedAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectMyFeedAsync(user);
        }
        
        public WebChatStream.ServiceReference1.Post[] SelectPostsByUser(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectPostsByUser(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectPostsByUserAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.SelectPostsByUserAsync(user);
        }
        
        public WebChatStream.ServiceReference1.Post[] SelectPostsByUID(int ID) {
            return base.Channel.SelectPostsByUID(ID);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post[]> SelectPostsByUIDAsync(int ID) {
            return base.Channel.SelectPostsByUIDAsync(ID);
        }
        
        public WebChatStream.ServiceReference1.Post SelectPostByID(int id) {
            return base.Channel.SelectPostByID(id);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Post> SelectPostByIDAsync(int id) {
            return base.Channel.SelectPostByIDAsync(id);
        }
        
        public void InsertDM(WebChatStream.ServiceReference1.DMessage dMessage) {
            base.Channel.InsertDM(dMessage);
        }
        
        public System.Threading.Tasks.Task InsertDMAsync(WebChatStream.ServiceReference1.DMessage dMessage) {
            return base.Channel.InsertDMAsync(dMessage);
        }
        
        public WebChatStream.ServiceReference1.User[] GetAllDMChats(WebChatStream.ServiceReference1.User main) {
            return base.Channel.GetAllDMChats(main);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> GetAllDMChatsAsync(WebChatStream.ServiceReference1.User main) {
            return base.Channel.GetAllDMChatsAsync(main);
        }
        
        public WebChatStream.ServiceReference1.DMessage[] SelectAllDMsChat(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.SelectAllDMsChat(main, chatted);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.DMessage[]> SelectAllDMsChatAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.SelectAllDMsChatAsync(main, chatted);
        }
        
        public bool AreChatting(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.AreChatting(main, chatted);
        }
        
        public System.Threading.Tasks.Task<bool> AreChattingAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.AreChattingAsync(main, chatted);
        }
        
        public WebChatStream.ServiceReference1.DMessage[] SelectUnSeenDM(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.SelectUnSeenDM(main, chatted);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.DMessage[]> SelectUnSeenDMAsync(WebChatStream.ServiceReference1.User main, WebChatStream.ServiceReference1.User chatted) {
            return base.Channel.SelectUnSeenDMAsync(main, chatted);
        }
        
        public int GetChatsDMUpdateState(WebChatStream.ServiceReference1.User main) {
            return base.Channel.GetChatsDMUpdateState(main);
        }
        
        public System.Threading.Tasks.Task<int> GetChatsDMUpdateStateAsync(WebChatStream.ServiceReference1.User main) {
            return base.Channel.GetChatsDMUpdateStateAsync(main);
        }
        
        public WebChatStream.ServiceReference1.Group GetGroupByID(int groupID) {
            return base.Channel.GetGroupByID(groupID);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group> GetGroupByIDAsync(int groupID) {
            return base.Channel.GetGroupByIDAsync(groupID);
        }
        
        public WebChatStream.ServiceReference1.Group[] GetGroupsByName(string name) {
            return base.Channel.GetGroupsByName(name);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> GetGroupsByNameAsync(string name) {
            return base.Channel.GetGroupsByNameAsync(name);
        }
        
        public void InsertGroup(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User creator) {
            base.Channel.InsertGroup(group, creator);
        }
        
        public System.Threading.Tasks.Task InsertGroupAsync(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User creator) {
            return base.Channel.InsertGroupAsync(group, creator);
        }
        
        public void UpdateGroup(WebChatStream.ServiceReference1.Group group) {
            base.Channel.UpdateGroup(group);
        }
        
        public System.Threading.Tasks.Task UpdateGroupAsync(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.UpdateGroupAsync(group);
        }
        
        public void DeleteGroup(WebChatStream.ServiceReference1.Group group) {
            base.Channel.DeleteGroup(group);
        }
        
        public System.Threading.Tasks.Task DeleteGroupAsync(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.DeleteGroupAsync(group);
        }
        
        public WebChatStream.ServiceReference1.GMember InsertGMemeber(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User user) {
            return base.Channel.InsertGMemeber(group, user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMember> InsertGMemeberAsync(WebChatStream.ServiceReference1.Group group, WebChatStream.ServiceReference1.User user) {
            return base.Channel.InsertGMemeberAsync(group, user);
        }
        
        public void DeleteGMember(WebChatStream.ServiceReference1.GMember member) {
            base.Channel.DeleteGMember(member);
        }
        
        public System.Threading.Tasks.Task DeleteGMemberAsync(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.DeleteGMemberAsync(member);
        }
        
        public void UpdateGMemberStatus(WebChatStream.ServiceReference1.GMember member) {
            base.Channel.UpdateGMemberStatus(member);
        }
        
        public System.Threading.Tasks.Task UpdateGMemberStatusAsync(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.UpdateGMemberStatusAsync(member);
        }
        
        public WebChatStream.ServiceReference1.GMember[] GetGroupMembers(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetGroupMembers(group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMember[]> GetGroupMembersAsync(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetGroupMembersAsync(group);
        }
        
        public WebChatStream.ServiceReference1.User[] SelectGroupAdmins(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGroupAdmins(group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectGroupAdminsAsync(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGroupAdminsAsync(group);
        }
        
        public WebChatStream.ServiceReference1.User[] SelectGroupNonAdmins(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGroupNonAdmins(group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.User[]> SelectGroupNonAdminsAsync(WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGroupNonAdminsAsync(group);
        }
        
        public bool IsGroupAdmin(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.IsGroupAdmin(member);
        }
        
        public System.Threading.Tasks.Task<bool> IsGroupAdminAsync(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.IsGroupAdminAsync(member);
        }
        
        public bool IsGroupMember(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.IsGroupMember(member);
        }
        
        public System.Threading.Tasks.Task<bool> IsGroupMemberAsync(WebChatStream.ServiceReference1.GMember member) {
            return base.Channel.IsGroupMemberAsync(member);
        }
        
        public WebChatStream.ServiceReference1.GMessage InsertGMessage(WebChatStream.ServiceReference1.GMessage message) {
            return base.Channel.InsertGMessage(message);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage> InsertGMessageAsync(WebChatStream.ServiceReference1.GMessage message) {
            return base.Channel.InsertGMessageAsync(message);
        }
        
        public void DeleteGMessage(WebChatStream.ServiceReference1.GMessage message) {
            base.Channel.DeleteGMessage(message);
        }
        
        public System.Threading.Tasks.Task DeleteGMessageAsync(WebChatStream.ServiceReference1.GMessage message) {
            return base.Channel.DeleteGMessageAsync(message);
        }
        
        public void UpdateGMessage(WebChatStream.ServiceReference1.GMessage message) {
            base.Channel.UpdateGMessage(message);
        }
        
        public System.Threading.Tasks.Task UpdateGMessageAsync(WebChatStream.ServiceReference1.GMessage message) {
            return base.Channel.UpdateGMessageAsync(message);
        }
        
        public WebChatStream.ServiceReference1.GMessage[] SelectGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGMessages(user, group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> SelectGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.SelectGMessagesAsync(user, group);
        }
        
        public WebChatStream.ServiceReference1.GMessage[] GetGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetGMessages(user, group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> GetGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetGMessagesAsync(user, group);
        }
        
        public WebChatStream.ServiceReference1.GMessage[] GetUnSeenGMessages(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetUnSeenGMessages(user, group);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.GMessage[]> GetUnSeenGMessagesAsync(WebChatStream.ServiceReference1.User user, WebChatStream.ServiceReference1.Group group) {
            return base.Channel.GetUnSeenGMessagesAsync(user, group);
        }
        
        public WebChatStream.ServiceReference1.Group[] GetMyGroups(WebChatStream.ServiceReference1.User user) {
            return base.Channel.GetMyGroups(user);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> GetMyGroupsAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.GetMyGroupsAsync(user);
        }
        
        public int GetMyGroupsUpdateState(WebChatStream.ServiceReference1.User user) {
            return base.Channel.GetMyGroupsUpdateState(user);
        }
        
        public System.Threading.Tasks.Task<int> GetMyGroupsUpdateStateAsync(WebChatStream.ServiceReference1.User user) {
            return base.Channel.GetMyGroupsUpdateStateAsync(user);
        }
        
        public WebChatStream.ServiceReference1.Group[] SearchPublicGroups(string groupName) {
            return base.Channel.SearchPublicGroups(groupName);
        }
        
        public System.Threading.Tasks.Task<WebChatStream.ServiceReference1.Group[]> SearchPublicGroupsAsync(string groupName) {
            return base.Channel.SearchPublicGroupsAsync(groupName);
        }
    }
}
